using ProcessusParent.Abstractions;
using ProcessusParent.Domain;

namespace ProcessusParent.Application;

public sealed class ParentWorkflow : IParentWorkflow
{
    private readonly IConsole _console;
    private readonly IProjectContextProvider _projectContextProvider;
    private readonly ITextFileWriter _textFileWriter;
    private readonly IProcessLauncher _processLauncher;

    public ParentWorkflow(
        IConsole console,
        IProjectContextProvider projectContextProvider,
        ITextFileWriter textFileWriter,
        IProcessLauncher processLauncher)
    {
        _console = console;
        _projectContextProvider = projectContextProvider;
        _textFileWriter = textFileWriter;
        _processLauncher = processLauncher;
    }

    public int RunDefaultScenario()
    {
        if (!_projectContextProvider.TryGetProjectContext(out ProjectContext? context, out string errorMessage))
        {
            _console.WriteErrorLine(errorMessage);
            return 1;
        }

        if (context is null)
        {
            _console.WriteErrorLine("Project context is unavailable.");
            return 1;
        }

        ProcessLaunchResult helloWorldResult = _processLauncher.Launch(
            new ProcessLaunchRequest(
                context.ConsoleHelloWorldExecutablePath,
                "Alice 3000",
                UseShellExecute: false,
                Verb: null,
                WaitForExit: false,
                ParentDelayMilliseconds: 0));

        if (!EnsureSuccess(helloWorldResult, "ConsoleHelloWorld"))
        {
            return 1;
        }

        _console.WriteLine("Parent process continues after child launch.");

        ProcessLaunchResult explorerResult = _processLauncher.Launch(
            new ProcessLaunchRequest(
                "explorer.exe",
                "C:\\Windows",
                UseShellExecute: true,
                Verb: null,
                WaitForExit: true,
                ParentDelayMilliseconds: 2000));

        if (!EnsureSuccess(explorerResult, "explorer.exe"))
        {
            return 1;
        }

        string noteFilePath = Path.Combine(context.SolutionRoot, "note-q5.txt");
        _textFileWriter.WriteAllText(noteFilePath, "Test file generated by ProcessusParent.");

        ProcessLaunchResult notepadResult = _processLauncher.Launch(
            new ProcessLaunchRequest(
                "notepad.exe",
                $"\"{noteFilePath}\"",
                UseShellExecute: true,
                Verb: null,
                WaitForExit: true,
                ParentDelayMilliseconds: 2000));

        if (!EnsureSuccess(notepadResult, "notepad.exe"))
        {
            return 1;
        }

        ProcessLaunchResult exploreVerbResult = _processLauncher.Launch(
            new ProcessLaunchRequest(
                "C:\\Windows",
                Arguments: null,
                UseShellExecute: true,
                Verb: "explore",
                WaitForExit: true,
                ParentDelayMilliseconds: 2000));

        if (!EnsureSuccess(exploreVerbResult, "C:\\Windows (explore)"))
        {
            return 1;
        }

        ProcessLaunchResult openVerbResult = _processLauncher.Launch(
            new ProcessLaunchRequest(
                "C:\\Windows\\win.ini",
                Arguments: null,
                UseShellExecute: true,
                Verb: "open",
                WaitForExit: true,
                ParentDelayMilliseconds: 2000));

        if (!EnsureSuccess(openVerbResult, "C:\\Windows\\win.ini (open)"))
        {
            return 1;
        }

        _console.WriteLine("Parent process completed.");
        return 0;
    }

    private bool EnsureSuccess(ProcessLaunchResult result, string operationName)
    {
        if (result.Success)
        {
            return true;
        }

        _console.WriteErrorLine(
            $"Operation failed for {operationName}: {result.ErrorMessage ?? "Unknown error."}");
        return false;
    }
}
