using ProcessusParent.Abstractions;
using ProcessusParent.Domain;

namespace ProcessusParent.Application;

public sealed class ParentWorkflow : IParentWorkflow
{
    private readonly IConsole _console;
    private readonly IProjectContextProvider _projectContextProvider;
    private readonly ITextFileWriter _textFileWriter;
    private readonly IProcessLauncher _processLauncher;
    private readonly IInteractiveMenu _interactiveMenu;

    public ParentWorkflow(
        IConsole console,
        IProjectContextProvider projectContextProvider,
        ITextFileWriter textFileWriter,
        IProcessLauncher processLauncher,
        IInteractiveMenu interactiveMenu)
    {
        _console = console;
        _projectContextProvider = projectContextProvider;
        _textFileWriter = textFileWriter;
        _processLauncher = processLauncher;
        _interactiveMenu = interactiveMenu;
    }

    public int RunDefaultScenario()
    {
        if (!_projectContextProvider.TryGetProjectContext(out ProjectContext? context, out string errorMessage))
        {
            _console.WriteErrorLine(errorMessage);
            return 1;
        }

        if (context is null)
        {
            _console.WriteErrorLine("Project context is unavailable.");
            return 1;
        }

        string noteFilePath = Path.Combine(context.SolutionRoot, "note-q5.txt");
        _textFileWriter.WriteAllText(noteFilePath, "Test file generated by ProcessusParent.");

        IReadOnlyList<LaunchMenuOption> options = BuildLaunchOptions(context, noteFilePath);

        while (true)
        {
            int selectedIndex = _interactiveMenu.PromptSelection(
                "Interactive Process Launcher",
                options.Select(option => option.Label).ToArray());

            LaunchMenuOption selectedOption = options[selectedIndex];
            if (selectedOption.IsExitOption)
            {
                _console.Clear();
                _console.WriteLine("Interactive launcher stopped.");
                return 0;
            }

            _console.Clear();
            ProcessLaunchRequest? request = selectedOption.Request;
            if (request is null)
            {
                _console.WriteErrorLine("No launch request configured for the selected option.");
                WaitForMenuReturn();
                continue;
            }

            ProcessLaunchResult result = _processLauncher.Launch(request);
            if (!EnsureSuccess(result, selectedOption.Label))
            {
                WaitForMenuReturn();
                continue;
            }

            WaitForMenuReturn();
        }
    }

    private IReadOnlyList<LaunchMenuOption> BuildLaunchOptions(ProjectContext context, string noteFilePath)
    {
        return
        [
            new LaunchMenuOption(
                "Launch ConsoleHelloWorld",
                new ProcessLaunchRequest(
                    context.ConsoleHelloWorldExecutablePath,
                    "Alice 3000",
                    UseShellExecute: false,
                    Verb: null,
                    WaitForExit: false,
                    ParentDelayMilliseconds: 0),
                IsExitOption: false),
            new LaunchMenuOption(
                "Launch explorer.exe (C:\\Windows)",
                new ProcessLaunchRequest(
                    "explorer.exe",
                    "C:\\Windows",
                    UseShellExecute: true,
                    Verb: null,
                    WaitForExit: false,
                    ParentDelayMilliseconds: 0),
                IsExitOption: false),
            new LaunchMenuOption(
                "Launch notepad.exe (note-q5.txt)",
                new ProcessLaunchRequest(
                    "notepad.exe",
                    $"\"{noteFilePath}\"",
                    UseShellExecute: true,
                    Verb: null,
                    WaitForExit: false,
                    ParentDelayMilliseconds: 0),
                IsExitOption: false),
            new LaunchMenuOption(
                "Launch calc.exe",
                new ProcessLaunchRequest(
                    "calc.exe",
                    Arguments: null,
                    UseShellExecute: true,
                    Verb: null,
                    WaitForExit: false,
                    ParentDelayMilliseconds: 0),
                IsExitOption: false),
            new LaunchMenuOption(
                "Open C:\\Windows\\win.ini (default editor)",
                new ProcessLaunchRequest(
                    "C:\\Windows\\win.ini",
                    Arguments: null,
                    UseShellExecute: true,
                    Verb: "open",
                    WaitForExit: false,
                    ParentDelayMilliseconds: 0),
                IsExitOption: false),
            new LaunchMenuOption(
                "Quit",
                Request: null,
                IsExitOption: true)
        ];
    }

    private void WaitForMenuReturn()
    {
        _console.WriteLine(string.Empty);
        _console.WriteLine("Press any key to return to the menu.");
        _console.ReadKey(intercept: true);
    }

    private bool EnsureSuccess(ProcessLaunchResult result, string operationName)
    {
        if (result.Success)
        {
            return true;
        }

        _console.WriteErrorLine(
            $"Operation failed for {operationName}: {result.ErrorMessage ?? "Unknown error."}");
        return false;
    }
}
